### 获取用户信息
POST http://localhost:8082
Content-Type: application/json

{
  "service": "as.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}
###
POST http://localhost:8081
Content-Type: application/json

{
  "service": "as.rpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [100, "abner"]
}

### mock
POST http://localhost:8081
Content-Type: application/json

{
  "service": "as.rpc.demo.api.UserService",
  "methodSign": "toString",
  "args": []
}

### 获取订单信息
POST http://localhost:8081
Content-Type: application/json

{
  "service": "as.rpc.demo.api.OrderService",
  "methodSign": "findById@1_int",
  "args": [300]
}

###
GET http://localhost:8088/?id=111